[project]
name = "rag-langgraph-template"
version = "0.0.1"
description = "A RAG agent in LangGraph."
authors = []
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "langchain>=1.0,<2.0",
    "langchain-core>=1.0,<2.0",
    "langchain-classic>=1.0,<2.0",
    "langchain-openai>=1.0,<2.0",
    "langchain-community>=0.4,<0.5",
    "langchain-chroma>=1.0",
    "langgraph>=1.0,<2.0",
    "langgraph-sdk>=0.4",
    "supabase>=2.13.0,<3.0.0",
    "python-dotenv>=1.0.1",
    "msgspec>=0.18.6",
]

[project.optional-dependencies]
dev = ["mypy>=1.11.1", "ruff>=0.6.1"]

[build-system]
requires = ["setuptools>=73.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["retrieval_graph", "ingestion_graph", "shared"]
[tool.setuptools.package-dir]
"langgraph.templates.retrieval_graph" = "src/retrieval_graph"
"langgraph.templates.ingestion_graph" = "src/ingestion_graph"
"retrieval_graph" = "src/retrieval_graph"
"ingestion_graph" = "src/ingestion_graph"
"shared" = "src/shared"

[tool.setuptools.package-data]
"*" = ["py.typed"]

[tool.ruff]
lint.select = ["E", "F", "I", "D", "D401", "T201", "UP"]
lint.ignore = ["UP006", "UP007", "UP035", "D417", "E501"]
[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "UP"]
[tool.ruff.lint.pydocstyle]
convention = "google"
[tool.pytest.ini_options]
pythonpath = ["src"]
